name: proj_clean_arch
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1
  flutter:
    sdk: flutter
  auto_route: ^5.0.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6

dev_dependencies:
  auto_route_generator: ^5.0.1
  mobx_codegen: ^2.0.7
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
